source 'https://rubygems.org'

gem 'rails', '~> 5.2.0'
gem 'sqlite3'

gem 'resizing-rails', path: '../../'
gem 'resizing', path: '../../../resizing-gem'

group :assets do
  # gem 'sassc-rails', '~> 2.1'
  # gem 'coffee-rails', '~> 4.0'

  # # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # # gem 'therubyracer'

  # gem 'uglifier', '>= 1.3'
end

group :development do
  gem 'foreman'
end
